CREATE TABLE [dbo].[Conversions]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(), 
    [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(), 
    [Rate] DECIMAL(10, 9) NOT NULL, 
    [Origin] INT NOT NULL, 
    [Destination] INT NOT NULL
)
